<a href="https://colab.research.google.com/github/soyeong792/Machine-Learning-Basics/blob/main/13_Tensorflow%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%9C_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%ED%9B%88%EB%A0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

References:

https://colab.research.google.com/github/rickiepark/
python-machine-learning-book-3rd-edition/blob/master/ch13/ch13_part1.ipynb
https://colab.research.google.com/github/rickiepark/python-machine-learning-book-3rd-edition/blob/master/ch13/ch13_part2.ipynb

## Tensorflow 처음 시작하기

In [1]:
import tensorflow as tf
import numpy as np

print("텐서플로 버전:", tf.__version__)

텐서플로 버전: 2.7.0


## 텐서 만들기

- array to tensor

In [3]:
a = np.array([1,2,3], dtype=np.int32)
b = [4,5,6]

#-------------------------------
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
#-------------------------------

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


- ones

In [4]:
t_ones = tf.ones((2,3)) #shape
t_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

- tf.fill 함수는 원하는 스칼라 값으로 채워진 텐서를 만듦

In [5]:
tf.fill((2,3),1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>