<a href="https://colab.research.google.com/github/soyeong792/Machine-Learning-Basics/blob/main/13_Tensorflow%EB%A5%BC_%EC%82%AC%EC%9A%A9%ED%95%9C_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%ED%9B%88%EB%A0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

References:

https://colab.research.google.com/github/rickiepark/
python-machine-learning-book-3rd-edition/blob/master/ch13/ch13_part1.ipynb
https://colab.research.google.com/github/rickiepark/python-machine-learning-book-3rd-edition/blob/master/ch13/ch13_part2.ipynb

## Tensorflow 처음 시작하기

In [1]:
import tensorflow as tf
import numpy as np

print("텐서플로 버전:", tf.__version__)

텐서플로 버전: 2.7.0


## 텐서 만들기

- array to tensor

In [3]:
a = np.array([1,2,3], dtype=np.int32)
b = [4,5,6]

#-------------------------------
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
#-------------------------------

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


- ones

In [4]:
t_ones = tf.ones((2,3)) #shape
t_ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

- tf.fill 함수는 원하는 스칼라 값으로 채워진 텐서를 만듦

In [5]:
tf.fill((2,3),1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

- tf.one_hot

In [6]:
tf.one_hot([0,1,2],4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

## 텐서의 수학 연산
- `tf.multiply`, `tf.math.reduce_mean`, `tf.linalg.matmul`,`tf.norm` 함수

In [ ]:
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5,2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5,2), mean=0.0, stddev=1.0)

t3 = tf.multiply(t1,t2).numpy()
print(t3)

t4 = tf.math.reduce_mean(t1,axis=0)
print(t4)

t5 = tf.linalg.matmul(t1,t2,transpose_b=True).numpy() #b가 transpose 됨.
t5_1 = t1 @ tf.transpose(t2) # @과 matmul은 같음.
print(t5)
print(t5_1) #same as t5

t6 = tf.linalg.matmul(t1,t2,transpose_a=True).numpy() #a가 transpose 됨.
print(t6)

t7 = tf.norm(t1, ord=2, axis=1).numpy()
print(t7)

- `tf.experimental.numpy` 모듈 아래에서 넘파이 호환 API를 사용할 수 있다.

In [25]:
import tensorflow.experimental.numpy as tnp
tnp.experimental_enable_numpy_behavior()

tn1 = tnp.array(t1)
tn2 = tnp.array(t2)
print(tnp.dot(tn1, tn2.T)) #np.dot

tf.Tensor(
[[-1.1436033   1.1154624  -0.8695717  -0.3210435   0.8555103 ]
 [ 0.2480186  -0.19149339  0.2504958  -0.0644026  -0.3307204 ]
 [-0.47782415  0.40717956 -0.43562764  0.02238911  0.5270062 ]
 [ 0.52479297 -0.23352614  0.74080014 -0.5925749  -1.1940588 ]
 [-0.09918742  0.26019508  0.12526006 -0.46231267 -0.39642125]], shape=(5, 5), dtype=float32)


- `split()`,`stack()`,`concatenate()` 함수